# Generated by Django 4.0.1 on 2022-01-12 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Project',
        ),
    ]
